### ISSUE TITLE
Notification, "vibrate off" not possible

### ISSUE THREAD

**Issue by jparrot99** [citiususc/calendula#120]
It is possible to choose Ringtone "None", but the phone still vibrates when the notification occurs. I would like to set a notification that is only "visible", and makes no sound at all.

**Comment by scruloose** [comment]
This is a good point!

Also, even when the user has selected an audible notification, they don't necessarily want vibration as well. For example, if I choose a soft chime for my notification tone and turn the volume fairly low so that it won't wake someone sleeping in the same room, but then the phone is vibrating and making a buzzing racket on the table, that's annoying.

Why not offer vibrate options in the app's notifications settings? There are four options that might make sense: never vibrate; only vibrate when alarm is audible; only vibrate when alarm is *not* audible; always vibrate. Let the user choose!

**Comment by Sparow199** [comment]
I think that disabling vibration for database download will bell better for UX because it's trigger a new vibration when the status bar is updated. (Tested on Android API 27).
