### ISSUE TITLE
Cannot modify an existing med

### ISSUE THREAD

**Issue by pablormier** [citiususc/calendula#13]
After editing an existing med, it is still listed with the old information under the medical kit tab.

**Comment by angelpinheiro** [comment]
Probably med is edited and saved, but list view is not updated. This is because med is saved through medicine.save() method instead of Persistence.instance().save(medicine) method, wich fires an event and causes the list update.

https://github.com/citiususc/calendula/blob/master/Calendula/src/main/java/es/usc/citius/servando/calendula/activities/MedicinesActivity.java#L102
