### ISSUE TITLE
Feature req. :allow custom made interval times, for schedules

### ISSUE THREAD

**Issue by GintokiHub** [citiususc/calendula#135]
Currently I am in a bit of a pinch because I take a certain medication; not every 4 OR 6 hours, but need to take or every 5 hours.

My suggestion would be a *custom* button at the bitten of the normally advised medication intervals called custom.
In which you could have total control in how regularly you have to take something.
SAY: every 7 hours and 14minutes.

I have to say you do great work.

**Comment by ontherunvaro** [comment]
Hi,

This is clearly something that's missing and we'll do our best to implement it.
In the meantime, let me suggest a workaround that, while laborious, will let you receive the notifications.

Assuming you would start taking your meds on a Monday at 00:00, let's plot how the intakes would be distributed:

|Day|Intake 1|Intake 2|Intake 3|Intake 4|Intake 5|
|---|---|---|---|---|---|
|Mon| 00:00 |05:00| 10:00 |15:00| 20:00|
|Tue |1:00 |6:00 |11:00 |16:00 |21:00|
|Wed |2:00| 7:00 |12:00 |17:00| 22:00|
|Thu  |3:00 |8:00 |13:00 |18:00 |23:00|
|Fri    |4:00| 9:00 |14:00| 19:00| |
|Sat| 00:00 |05:00| 10:00 |15:00| 20:00|

As you can see, the intakes start repeating after 4 days. This, however cumbersome, can be modeled using the "period + rest" style of schedule. This would require:

- Creating a routine for each hour of the day, i.e. 24 routines.
- Creating 5 different period+rest schedules, each of them active for 1 day with 4 days of rest.

Each of those schedules should use the times on the rows of the above table, so that combining all of them should give you notifications every 5 hours all week round. As I said before, this is far from pretty, but it can work for you until we add custom times.

Cheers, and sorry.

**Comment by GintokiHub** [comment]
thanks for the elaborate temporary work around you made!

**Comment by ontherunvaro** [comment]
@GintokiHub We just released Calendula 2.5.9 which, between other improvements, allows setting repeating schedules for 5 and 10 hour intervals. We still have custom intervals in mind for the future though.
