### ISSUE TITLE
Collapse/expand behaviour and color of top section at Home tab

### ISSUE THREAD

**Issue by rrodrigueznt** [citiususc/calendula#66]
Hi! I would like to avoid background color of top section at Home tab. When collapsed, it is backgrounded with the color of the current patient while schedules for all patients are shown. That's is confusing me! Also, I would like to respect the collapsed status once selected even though I'll move to other tabs: for instance, if I navigate to Medicines and go back to Home, I would like to get the top section collapsed when I collapsed it before going to Medicines.

Thanks!

**Comment by angelpinheiro** [comment]
Regarding the background color suggestion, i cant think on a better way of choosing a color for the top bar when collapsing. Keeping the image is not a good option because it can't be shown full size and the view becomes ugly. Choosing a patient-neutral color could be an option, but that color will change when scrolling right, and i think that will be more confusing and result in a less fluid UI.

Regarding the auto collapse/expand behavior, I see your point. I think we can keep the top bar collapsed if you collapsed it before and apply the current approach in other case. What does not make much sense to me is keeping the panel expanded on the routines/medkit/schedules tabs, since you usually need that space to comfortably inspect those lists.

**Comment by rrodrigueznt** [comment]
When you go to tabs on the right, they show information only about the current patient. Thus, it makes sense that the background color of the top section changes provided you are in a multi-patient environment. In this scenario, when information at Home tab shows that concerning to several patients, a patient-neutral color could make perfect sense. This won't be true if there is only one patient in the system. In this case, all top sections will coherently have the same background color. WDTY?

I do agree on the second paragraph! Thanks!

**Comment by angelpinheiro** [comment]
I think it is a problem of user preferences, and to achieve a solution that works well for everybody it's necessary to provide a way to personalize that behavior. We intended to add a better home "background-image" selection mechanism and I think we can go over this at the same time. I will leave the issue open to take care of them in future releases.

**Comment by rrodrigueznt** [comment]
One more comment on this issue: there is a basic difference between the Home tab and the others: in a multi-patient environment, Home tab shows information about taken and pending doses for all of them. For me is clearer now that it shouldn't be ever allowed to set a color background for the Home tab equal to any of the patients in a given installation. Even more, as Ángel said in a previous message, I would like to have a "patient neutral" design for that tab. Thanks!
