### ISSUE TITLE
Want some help please reply

### ISSUE THREAD

**Issue by PramUkesh** [citiususc/calendula#79]
Hi I really liked your work
Since I was new to programming,
I want some help to reimplement the patients detail activity as profile user activity
Things I need are:
First I need profile image click listener so that when user clicks on image it opens a profile activity.
Since I implemented fire base authentication it should show default user name email and icon
Before login and after login the authenticated email used for authentication
And changeable name and avatar and avatar BG color like you implemented in patients detail activity
Since it has server back end all saved instances like chosen avatar and avatar BG color and name to server
If you want to help me please reply I can send my source code please remember that I is a non profit project I don't earn any penny unless it is for server maintenance through advertisements if you think it is for profit, remember that I don't have any income source as I was student who is passionate to learn coding even though my subjects entirely different from computer science please reply fast
Contact me at
N.bhargavvenky@gmail.com
Fb@pramukeshvenky
Whatsapp@9700717344(with country code +919700717344)

**Comment by ontherunvaro** [comment]
Hi @PramUkesh,
Unfortunately, we do not provide support for developers, for-profit or otherwise. There are plenty of resources both off and online for aspiring Android developers such as you.

If you do use Calendula as a base for your projects, please remember it is licensed under the [GNU GPL License v3](https://github.com/citiususc/calendula/blob/master/LICENSE.md), and, as such, you're obligated to publish your modifications under the same license.

I've also edited your post to remove personal information.

Thank you for your interest in Calendula, and good luck in your projects!
