### ISSUE TITLE
Database Download

### ISSUE THREAD

**Issue by BryanKylan** [citiususc/calendula#93]
On Tecno Camon C8  there is always an error when downloading and setting up the AEMP database and also a few range of devices expirience the same error

**Comment by BryanKylan** [comment]
On Tecno Camon C8 there is always an error when downloading and setting up the AEMP database and also a few range of devices expirience the same error

**Comment by ontherunvaro** [comment]
Hello,

We are aware of this issue and already working to resolve it. It's a problem with a faulty implementation of permissions on some Android versions.

**Comment by BryanKylan** [comment]
So the problem is only on some android versions...am a young developer and
i will love to learn how you will resolve this issue

**Comment by ontherunvaro** [comment]
@BryanKylan theoretically, applications don't need the `WRITE_EXTERNAL_STORAGE` permission to download to the app's private folder in external storage ([this folder](https://developer.android.com/reference/android/app/DownloadManager.Request.html#setDestinationInExternalFilesDir(android.content.Context,%20java.lang.String,%20java.lang.String)))

However, some vendors don't seem to respect this, and the download crashes when we try to start it because it requires the permission.

Our solution is simple: we ask for this permission before the download.
