### ISSUE TITLE
Cannot add the project to android studio and make it editable.

### ISSUE THREAD

**Issue by Claude12** [citiususc/calendula#99]
Please can someone help and take me through the steps i am using android studio version 3.0.1

**Comment by angelpinheiro** [comment]
Hi @Claude12, have you followed the steps from the [getting started](https://github.com/citiususc/calendula#getting-started) section?. If so, could you provide more details about the specific problem you are having? I've just cloned the repo (develop branch), opened it with Android Studio 3.0.1, selected the "developDebug" build variant, and I had no problem compiling and running the app.

I would say it is due to some missing SDK component on your machine, but it is impossible to know without more information.
